### COMMON PARAMETERS
.build_job: &job_build
  stage: build
  dependencies:
    - download_upstream_db
  artifacts:
    expire_in: 1 hour
    paths:
      - result/*
  tags:
    - docker

.debian_script: &deb_script
  script:
    - export DEBFULLNAME='Inverse inc.'; dh_make --createorig -p fingerbank_$(cat $UPSTREAM_VERSION_FILE) -s -y -e info@inverse.ca
    - ci-build-pkg

.rhel_script: &rpm_script
  script:
    - yum install epel-release -y
    - tar c -zf upstream-db.tar $UPSTREAM_DB_FILE
    - ci-build-pkg

### STAGES
stages:
 - download
 - build
 - sign
 - publish

### VARIABLES
variables:
  UPSTREAM_DB_URL: https://api.fingerbank.org/api/v2/download/db
  UPSTREAM_DB_FILE: db/fingerbank_Upstream.db
  UPSTREAM_VERSION_FILE: /tmp/upstream_version.txt

### JOBS
# for debug purpose
before_script:
  - unset http_proxy ; unset https_proxy
  - env | grep ^CI_

download_upstream_db:
  image: buildpkg/debian:stretch
  stage: download
  # secret variable defined
  # API_KEY = fingerbank API KEY
  script:
    # get Upstream DB (not part of source)
    - curl --retry 3 --fail -X GET $UPSTREAM_DB_URL?key=$API_KEY --output $UPSTREAM_DB_FILE
    - apt install libreadonly-perl
    # get Upstream version from source code (workaround for https://gitlab.com/gitlab-org/gitlab-ce/issues/47517)
    - perl -I'lib/fingerbank' -M'Constant' -e 'print "$fingerbank::Constant::VERSION"' > $UPSTREAM_VERSION_FILE
  # pass artifact to build jobs
  artifacts:
    paths:
      - $UPSTREAM_DB_FILE
      - $UPSTREAM_VERSION_FILE

# we use YAML anchors to define same parameters for all builds
build_debian_stretch:
  image: buildpkg/debian:stretch
  <<: *job_build
  <<: *deb_script

build_centos_7:
  image: buildpkg/centos:7
  <<: *job_build
  <<: *rpm_script

sign:
  image: buildpkg/debian:stretch
  stage: sign
#  secret variables defined:
#    SIGN_USER: firstname.lastname@example.com
#    GPG_PRIVATE_KEY: `gpg --armor --export-secret-keys firstname.lastname@example.com`
  script:
    - ci-sign-pkg
  dependencies:
    - build_debian_stretch
    - build_centos_7
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  tags:
    - docker

pages:
  image: buildpkg/debian:stretch
  stage: publish
  variables:
    PAGES_DIR: public
  environment:
    name: PPA
    url: http://${CI_PROJECT_NAMESPACE}.gitlab.io/
  script:
    - ci-pages-ppa
    - ci-pages-home
    - ci-pages-tree
  dependencies:
    - sign
  artifacts:
    paths:
      - public
  tags:
    - docker
