################################################################################
# COMMON PARAMETERS
################################################################################
before_script:
  - unset http_proxy ; unset https_proxy
  - env | grep ^CI_

################################################################################
# STAGES
################################################################################
stages:
 - build_pkg
 - sign
 - publish
 - test

################################################################################
# VARIABLES
################################################################################
variables:
  PACKAGE_NAME: fingerbank
  DEB_PACKAGES_NAME: "['fingerbank']"
  RPM_PACKAGES_NAME: "['fingerbank']"

################################################################################
# TEMPLATES
################################################################################
.build_job:
  stage: build_pkg
  dependencies: []
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  tags:
    - docker

.debian_script:
  script:
    - make -e build_deb

.rpm_script:
  script:
    - make -e build_rpm


########################################
# JOBS
########################################
build_pkg_debian_bullseye:
  image: registry.gitlab.com/orange-opensource/gitlab-buildpkg/debian:bullseye
  extends:
    - .build_job
    - .debian_script

build_pkg_centos_8:
  image: registry.gitlab.com/orange-opensource/gitlab-buildpkg/centos:8
  extends:
    - .build_job
    - .rpm_script

sign:
  # only use when executor is docker
  image: registry.gitlab.com/orange-opensource/gitlab-buildpkg/debian:buster
  stage: sign
  # use secret variables defined in GitLab UI
  script:
    - ci-sign-pkg
  dependencies:
    - build_pkg_debian_bullseye
    - build_pkg_centos_8
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  tags:
    - shell

pages:
  # only use when executor is docker
  image: registry.gitlab.com/orange-opensource/gitlab-buildpkg/debian:buster
  stage: publish
  variables:
    PAGES_DIR: public
  environment:
    name: PPA
    url: http://${CI_PROJECT_NAMESPACE}.gitlab.io/
  script:
    - ci-pages-ppa
    - ci-pages-home
    - ci-pages-tree
  dependencies:
    - sign
  artifacts:
    expire_in: 1 day
    paths:
      - public
  tags:
    - shell

test_debian_bullseye:
  stage: test
  script:
    - cd vagrant/ ; vagrant up fbdeb9dev --provider=libvirt --destroy-on-error
  after_script:
    - cd vagrant/ ; vagrant destroy -f fbdeb9dev
    - rm -rf .vagrant/ roles/
  dependencies: []
  tags:
    - shell

test_centos_7:
  stage: test
  script:
    - cd vagrant/ ; vagrant up fbcendev --provider=libvirt --destroy-on-error
  after_script:
    - cd vagrant/ ; vagrant destroy -f fbcendev
    - rm -rf .vagrant/ roles/
  dependencies: []
  tags:
    - shell
