################################################################################
# COMMON PARAMETERS
################################################################################
before_script:
  - unset http_proxy ; unset https_proxy
  - env | grep ^CI_

################################################################################
# STAGES
################################################################################
stages:
 - build_pkg
 - sign
 - publish
 - test

################################################################################
# VARIABLES
################################################################################
variables:
  BUILDPKG_REGISTRY: registry.gitlab.com/orange-opensource/gitlab-buildpkg
  CENTOS_8_IMG: centos:8
  DEB_BULLSEYE_IMG: debian:bullseye
  DEB_BUSTER_IMG: debian:buster
  VAGRANT_DIR: vagrant
  ANSIBLE_FORCE_COLOR: 1

################################################################################
# TEMPLATES
################################################################################
.build_job:
  stage: build_pkg
  dependencies: []
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  tags:
    - docker-inverse

.debian_script:
  script:
    - make -e build_deb

.rpm_script:
  script:
    - make -e build_rpm


########################################
# JOBS
########################################
build_pkg_debian_bullseye:
  image: registry.gitlab.com/orange-opensource/gitlab-buildpkg/debian:bullseye
  extends:
    - .build_job
    - .debian_script

build_pkg_centos_8:
  image: registry.gitlab.com/orange-opensource/gitlab-buildpkg/centos:8
  extends:
    - .build_job
    - .rpm_script

sign:
  # only use when executor is docker
  image: registry.gitlab.com/orange-opensource/gitlab-buildpkg/debian:buster
  stage: sign
  # use secret variables defined in GitLab UI
  script:
    - ci-sign-pkg
  dependencies:
    - build_pkg_debian_bullseye
    - build_pkg_centos_8
  artifacts:
    expire_in: 1 day
    paths:
      - result/*
  tags:
    - shell

pages:
  # only use when executor is docker
  image: registry.gitlab.com/orange-opensource/gitlab-buildpkg/debian:buster
  stage: publish
  variables:
    PAGES_DIR: public
  environment:
    name: PPA
    url: http://${CI_PROJECT_NAMESPACE}.gitlab.io/
  script:
    - ci-pages-ppa
    - ci-pages-home
    - ci-pages-tree
  dependencies:
    - sign
  artifacts:
    expire_in: 1 day
    paths:
      - public
  tags:
    - shell

test_debian_bullseye:
  stage: test
  variables:
    VAGRANT_DOTFILE_PATH: /var/local/gitlab-runner/vagrant/vagrant-fb-debian-bullseye-dev
  script:
    - make -e -C $VAGRANT_DIR fbdeb11dev
  after_script:
    - make -e -C $VAGRANT_DIR halt-fbdeb11dev
  dependencies:
    - pages
  tags:
    - shell

test_el_8:
  stage: test
  variables:
    VAGRANT_DOTFILE_PATH: /var/local/gitlab-runner/vagrant/vagrant-fb-el-8-dev
  script:
    - make -e -C $VAGRANT_DIR fbel8dev
  after_script:
    - make -e -C $VAGRANT_DIR halt-fbel8dev
  dependencies:
    - pages
  tags:
    - shell
