---
- hosts: dev
  name: install fingerbank development packages
  become: True

  roles:
    - role: inverse_inc.gitlab_buildpkg_tools
      tags: ci
      vars:
        gitlab_buildpkg_tools__rpm_deps_repos:
          - name: packetfence-devel
            baseurl: http://inverse.ca/downloads/PacketFence
            extra_path: devel
            gpgkey_url: https://packetfence.org/downloads/RPM-GPG-KEY-PACKETFENCE-CENTOS
        gitlab_buildpkg_tools__deb_deps_repos:
          - name: packetfence-devel
            baseurl: http://inverse.ca/downloads/PacketFence
            gpgkey_url: http://inverse.ca/downloads/APT-GPG-KEY-PACKETFENCE-DEBIAN
            extra_path: debian-devel
            pool: stretch
          - name: packetfence
            baseurl: http://inverse.ca/downloads/PacketFence
            gpgkey_url: http://inverse.ca/downloads/APT-GPG-KEY-PACKETFENCE-DEBIAN
            pool: stretch